### PR TITLE
Migrate to Python 3 runtime of Google App Engine

### PR DESCRIPTION
**Pull request by aktech**
This migrates the application to Python3 runtime of Google App Engine.

- [x] Remove submodules
- [x] Remove vendor requirements
- [x] Use requirements.txt
- [x] Add `.gcloudignore`
- [x] Make application compatible with Python 3.7
- [x] Run app directly instead of Docker compose.

Further cleanups will happen in later Pull requests.

### CODE REVIEW

**Comment by asmeurer** [comment]
So the submodules aren't needed anymore?

**Comment by aktech** [comment]
Yes, they aren't needed anymore. We install everything via `requirements.txt`

**Comment by asmeurer** [comment]
I see. IIRC we were pinned to some commit between versions. We should make sure 0.7.5 doesn't break anything.

**Comment by aktech** [comment]
Yes, correct. I tried to break, but everything seems to work of what I tried: https://py3-runtime-dot-sympy-gamma-hrd.appspot.com/

**Comment by aktech** [comment]
I have tried all the possible cases I can think of and the tests passes as well. I'll merge this in next 48 hours if no objections.

**Comment by WaleedSaleh** [comment]
I would really thank you for this perfect work
but when running the app it is plain HTML there are no styles, whereas the styles respond with 200 status code.

**Comment by aktech** [comment]
@WaleedSaleh It could be a caching issue, can you try doing a Hard refresh on your browser (you can Google for your browser on how to do that.). Also just to confirm, can you share the command you are using to run the app?

**Comment by aktech** [comment]
@WaleedSaleh I see why you're seeing that error, you need to set `Debug=True` in `settings.py` for serving static files locally:
https://github.com/sympy/sympy_gamma/blob/17b9f0e8cb440c773b0875685f0d450d9e968fc3/app/settings.py#L26

**Comment by WaleedSaleh** [comment]
You're welcome, I used docker-compose up for running the app because when using "python mange.py runserver" this error occurs:

>   File "C:\Users\walee\OneDrive\Desktop\Freelance\sympy_gamma\venv\lib\site-packages\grpc\__init__.py", line 23, in <module>
>     from grpc._cython import cygrpc as _cygrpc
>   File "src\python\grpcio\grpc\_cython\cygrpc.pyx", line 27, in init grpc._cython.cygrpc
>   File "C:\Users\walee\AppData\Local\Programs\Python\Python37\lib\asyncio\__init__.py", line 39, in <module>
>     from .windows_events import *
>   File "C:\Users\walee\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_events.py", line 19, in <module>
>     from . import windows_utils
>   File "C:\Users\walee\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_utils.py", line 126, in <module>
>     class Popen(subprocess.Popen):
> TypeError: NoneType takes no arguments

**Comment by aktech** [comment]
@WaleedSaleh `docker-compose up` is the correct command. If you make the change suggested above it's should work.

**Comment by WaleedSaleh** [comment]
@aktech thank you, it worked with  **docker-compose up**

**Pull request merged**
