### PR TITLE
Test PR (do not merge)

### PR DESCRIPTION
**Pull request by asmeurer**
Opening a test PR with no changes to see if the Travis tests pass.

### CODE REVIEW

**Comment by ashutoshsaboo** [comment]
Seems like the build hasn't started yet - https://travis-ci.org/sympy/sympy_gamma/builds/116428696 . Some problem with Travis or with our code?

**Comment by ashutoshsaboo** [comment]
Because, otherwise the Travis CI Tests, are just of like around 1min-2min duration! :sweat_smile:

**Comment by asmeurer** [comment]
I believe the SymPy Gamma Travis tests share the same queue as the SymPy Travis tests, so it may take a while to start, unfortunately (only 10 builds can run at a time).

**Comment by ashutoshsaboo** [comment]
Yes, so this also failed. :/ How about if we mark that test as `@XFAIL`?

**Comment by asmeurer** [comment]
I think there is a real issue, as per #70.

**Comment by aktech** [comment]
Closing as Travis passes.

**Pull request closed without merging**
