### PR TITLE
Code for Issue #70 | fix plot() error

### PR DESCRIPTION
**Pull request by ashutoshsaboo**
Resolves and fixes issue #70 . 

This PR was started after #72 .

@asmeurer 

Same code Travis CI results - https://travis-ci.org/ashutoshsaboo/sympy_gamma

### CODE REVIEW

**Comment by ashutoshsaboo** [comment]
@asmeurer Is this good now? Can this be merged?

**Comment by asmeurer** [comment]
Yes, +1. I want to wait for the sympy/sympy_gamma Travis tests pass to merge, but +1 to do it as soon as they pass.

**Comment by ashutoshsaboo** [comment]
Yes, so the first commit has passed the Travis tests. @asmeurer

**Comment by ashutoshsaboo** [comment]
Hi @asmeurer . So this has passed all the Travis tests now. I guess after you merge this, you can restart the builds for #74 , #75 , #69 . Those will also pass the Travis tests after this is merged.

**Comment by ashutoshsaboo** [comment]
Thanks @asmeurer ! :smiley:

**Pull request merged**
