### PR TITLE
Solves & Fixes Issue #70 | plot() doesn't produce an error now

### PR DESCRIPTION
**Pull request by ashutoshsaboo**
@asmeurer .

This PR solves and fixes issue #70 . plot() no longer gives an error. The main error was because of the `numpy` and `django` version on my system, my local installation of `numpy` and `django` were very new version's in comparison to those compatible with SymPy Gamma, as of now. Re-installing the required versions of `numpy` and `django` solved the issue! Hence, I modified the test case file, as well as the requirements file. Now, plot() card in my local installation of SymPy Gamma doesn't produce any error, and displays the required graph.

Hence, this fixes & resolves issue #70 .

The same can be observed in this screenshot-:

selection_009

### CODE REVIEW

**Comment by ashutoshsaboo** [comment]
@asmeurer So, this has passed all the tests now. I guess it'll be better if you merge this PR - #72 first, and then you can merge PR - #69 , as both of them have passed all tests now.

**Comment by asmeurer** [comment]
I think the only change here should be the requirements.txt file. You have mixed in changes from other pull requests. Make sure when you start a new branch that you `git checkout master` first so that your branch is based off of master.

**Comment by ashutoshsaboo** [comment]
@asmeurer Ohh! So, what should I do now? I guess it'd be better for me to handle this once PR #69 is merged, because I guess it's files have only come here. Or is it fine like this?

**Comment by asmeurer** [comment]
Could you create a new pull request with a new branch, which is based off of master, with just the change to the requirements file. If the fix really is correct, the phantom.js change should not be necessary.

**Comment by ashutoshsaboo** [comment]
@asmeurer Actually as I said, the phatom.js change is required for the description I provided here (second last comment) #69 . That's the thing.

**Comment by asmeurer** [comment]
If the phantom.js change is needed then you haven't really fixed the issue, because all the phantom.js change does is disable the test. I am -1 to the phantom.js change.

**Comment by ashutoshsaboo** [comment]
Ohh @asmeurer . I'll try pushing a PR with only the requirements.txt change.

**Comment by ashutoshsaboo** [comment]
The `requirements.txt` fix at least fixed everything up on my local system. I have pushed a new PR. Now, let's see what happens.

**Comment by ashutoshsaboo** [comment]
So, I'll close this PR, since #70 is merged.

**Pull request closed without merging**
