### PR TITLE
Upgrade SymPy to 1.6

### LINKED ISSUE #155: Upgrade SymPy to latest version
The application will soon run on Python3 runtime #154 This needs to be done after that. This involves updating the version in requirements.txt and testing everything.

### PR DESCRIPTION
**Pull request by aktech**
- [x] Used Reciprocal instead of LogRule (as changed in this commit: https://github.com/sympy/sympy/commit/b7d400fb9f1604b3cfba4dd1a7fa2feef91ebf80)
- [x] Check `is_Integer` attr before accessing (due to MutableDenseMatrix has no attribute is_Integer)
- [x] Use random secret key in settings file.
- [x] Reorder imports and linting fixes.
- [x] Change `sympy.parsing.sympy_tokenize` -> `tokenize`

Fixes #155

### CODE REVIEW

**Comment by asmeurer** [comment]
Is going straight to 1.6 too much work?

**Comment by asmeurer** [comment]
Do we know what the test coverage is like for Gamma? Can we rely on the test suite or do we need to do a lot of manual testing as well?

**Comment by aktech** [comment]
> Is going straight to 1.6 too much work?

It seems there isn't. I thought there might be, so took the conservative approach. There was only a tokenisation change,  I have upgraded it to `1.6` now.

> Do we know what the test coverage is like for Gamma? Can we rely on the test suite or do we need to do a lot of manual testing as well?

We don't know a number as of yet, as most of the tests except a few unit tests, runs via casperjs and I am not sure how to get coverage from it (I'll create an issue for it).

I have mostly relied on those tests and some manual tests. The casperjs tests seems to test most of the complex functionalities like matrices, integration, differentiation and their steps, which I have tested manually (not the correctness, as it obviously depends on SymPy).

https://github.com/sympy/sympy_gamma/blob/e4d4523a3afa3d12867513644201006d2fb964c1/app/test/test_phantomjs.js#L30-L89

**Comment by aktech** [comment]
@asmeurer any other concerns?

**Comment by aktech** [comment]
> We should figure out how to automate the SymPy updating, so that it doesn't get out of date. Can we use one of those services that sends PRs when there are updates in your requirements.txt?

Yes, we can do that via Github's [Dependbot](https://dependabot.com/). It seems I don't have permission to integrate it, I have sent a request to add dependbot, you should have probably received it.

**Comment by aktech** [comment]
I'll merge this in next 48 hours if no objections.

**Pull request merged**
